require './app/resources/api_resource'
require './app/resources/author_resource'
require './app/resources/author_books_resource'
require './app/resources/authors_resource'
require './app/resources/book_resource'
require './app/resources/books_resource'
require './app/resources/serie_resource'
require './app/resources/series_resource'
