# frozen_string_literal: true
require './app/resources/api_resource'
require './app/resources/author_resource'
require './app/resources/author_books_resource'
require './app/resources/authors_resource'
require './app/resources/book_resource'
require './app/resources/books_resource'
require './app/resources/serie_resource'
require './app/resources/serie_books_resource'
require './app/resources/series_resource'
require './app/resources/signin_resource'
require './app/resources/signup_resource'
require './app/resources/user_resource'
