development: &default
  adapter: postgresql
  database: backend-development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: backend-test
